# Fetching the latest node image on alpine linux
FROM node:latest AS development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /react-app

# Installing dependencies
COPY ./package.json /react-app
RUN yarn install

# Copying all the files in our project
COPY . .

# Starting our application
CMD npm start
# docker run -d -it --rm -p 8000:3000 --name react-app-container my-react-app